name: gesture-recognition-tflite-rp2040
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pytorch::pytorch
  - tensorflow
  - matplotlib
  - numpy
  - cbor2
  - keras
  - mypy
  - black
  - tomli
  - zstd
  - pip
  - pip:
    - --editable .
