name: gesture-recognition-tflite-rp2040
channels:
  - conda-forge
  - pytorch-test
dependencies:
  - python=3.11.*
  - pytorch=2.4.*
  - tensorflow
  - matplotlib
  - numpy
  - cbor2
  - keras
  - mypy
  - black
  - pip
  - pip:
    - ai-edge-torch==0.1.1
    - --editable .
