name: gesture-recognition-rp2040
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.0
  - pytorch::pytorch
  - tensorflow
  - matplotlib
  - numpy
  - cbor2
  - keras
  - mypy
  - black
  - pip
  - pip:
    - --editable .
